global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'mongodb'
    target_groups:

      ## Hosts:
      # localhost:37017 = shard1 replica set member #1  (exporter: localhost:47017)
      # localhost:37018 = cluster mongos/router         (exporter: localhost:47018)
      # localhost:37019 = cluster config server         (exporter: localhost:47019)
      # localhost:37027 = shard1 replica set member #2  (exporter: localhost:47027)
      #
      # * Exporter localhost:9100 below = the prometheus 'node_exporter' it is only
      #   deployed once because all instances below are on the same host

      - targets: ['localhost:47017','localhost:9100']
        labels:
          alias: 'localhost:37017'
          nodetype: 'mongod'
          replset: 'shard1'
          cluster: 'exampleCluster'

      - targets: ['localhost:47027','localhost:9100']
        labels:
          alias: 'localhost:37027'
          nodetype: 'mongod'
          replset: 'shard1'
          cluster: 'exampleCluster'

      - targets: ['localhost:47018','localhost:9100']
        labels:
          alias: 'localhost:37018'
          nodetype: 'mongos'
          cluster: 'exampleCluster'

      - targets: ['localhost:47019','localhost:9100']
        labels:
          alias: 'localhost:37019'
          nodetype: 'config'
          cluster: 'exampleCluster'

